config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
 
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  # root "articles#index"
  root "home#index"
  
  devise_scope :user do  
    get '/users/sign_out' => 'devise/sessions#destroy'     
  end

  # scope "/:locale" do
  #   resources :users do 
  #     resources :topics
  #   end
  # end

  # resources :topics 
  resources :users

  resources :users do
    resources :topics do
      resources :likes
    end
  end

  resources :likes  
  
  resources :topics do 
    resources :comments
  end

  resources :users do
    resources :friendships
  end

  resources :friendships do
    member do
      get :delete
    end
  end

  resources :topics do
    member do
      get :show
    end
  end
  get '/users/', to: "users#show"
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :topic
  belongs_to :user
  validates :content,presence: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  skip_before_action :verify_authenticity_token

  def index
    @topic = Topic.find(params[:topic_id])
  end

  def new
    @topic  = Topic.find(params[:topic_id])
    @comment = @topic.comments.new
  end

	def create
    @topic  = Topic.find(params[:topic_id])
  	@comment = @topic.comments.new(comment_params)
  	@comment.save
    if @comment.save
      redirect_to root_path
  	end
	end

  def show
    @topic = Topic.find(params[:topic_id])
  end

	private

	def comment_params
  	params.require(:comment).permit(:content,:topic_id,:user_id).merge(user_id: current_user.id)
  end
end

 

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/create.html.erb
<div class="card my-1">
  <div class="card-body">
    <p class="font-weight-bold">Comments</p>
    <%=  form_with(model: @comment, url: topic_comments_url(@topic), method: :create, local: true, remote: true ) do |f| %>
      <div class="form-group">
        <%= f.label 'New comment' %>
        <%= f.text_area :content, class: 'form-control' %>
      </div>
      <%= f.submit 'Submit', class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/comments/index.html.erb
<h2>Comments</h2>
<% @topic.comments.each do |comment| %>
  <p>
    <strong>Comment:</strong>
    <%= comment.content %>
  </p>
<% end %>

<div class="card my-1">
  <div class="card-body">
    <p class="font-weight-bold">Comments</p>
    <%= form_with(model: [@topic, @topic.comments.build]) do |f| %>
      <div class="form-group">
        <%= f.label 'New comment' %>
        <%= f.text_area :content, class: 'form-control' %>
      </div>
      <%= f.submit 'Submit', class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/comments/new.html.erb
<%=  form_with(model: @comment, url: user_topic_comments_path(@topic), method: :create,local: true, remote: true) do |form| %>
  <div class="form-group">
    <%= form.label :content %>
    <%= form.text_area :content, class: 'form-control' %>
  </div>

  <div class="form-group">
  <%= form.submit "add comment", class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/comments/show.html.erb
<h2>Comments</h2>
<% @topic.comments.each do |comment| %>
  <p>
    <strong>Comment:</strong>
    <%= comment.content %>
  </p>
<% end %>

<div class="card my-1">
  <div class="card-body">
    <p class="font-weight-bold">Comments</p>
    <%= form_with(model: [@topic, @topic.comments.build]) do |f| %>
      <div class="form-group">
        <%= f.label 'New comment' %>
        <%= f.text_area :content, class: 'form-control' %>
      </div>
      <%= f.submit 'Submit', class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>