config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
 
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  # root "articles#index"
  root "home#index"
  
  devise_scope :user do  
    get '/users/sign_out' => 'devise/sessions#destroy'     
  end

  # scope "/:locale" do
  #   resources :users do 
  #     resources :topics
  #   end
  # end

  # resources :topics 
  resources :users

  resources :users do
    resources :topics do
      resources :likes
    end
  end

  resources :likes  
  
  resources :topics do 
    resources :comments
  end

  resources :users do
    resources :friendships
  end

  resources :friendships do
    member do
      get :delete
    end
  end

  resources :topics do
    member do
      get :show
    end
  end
  get '/users/', to: "users#show"
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the user here. For example:
    #
    #return unless user.admin?
    # can :read, :all
      return unless user.super_admin?
      can :manage, :all
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
	devise :database_authenticatable,:recoverable, :rememberable, :validatable

	ROLES = %w{super_admin admin}

  def super_admin?
    role == "super_admin"
  end

  def admin?
    role == "admin"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :topics
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :topic
  belongs_to :user
  validates :content,presence: true
end

app/models/friendship.rb
class Friendship < ApplicationRecord
	
	belongs_to :sender, class_name: 'User', foreign_key: 'sender_id'
	belongs_to :receiver, class_name: 'User', foreign_key: 'receiver_id'

end

app/models/like.rb
class Like < ApplicationRecord
  validates :user_id,uniqueness: {scope: :topic_id}
  belongs_to :user
  belongs_to :topic
end

app/models/topic.rb
class Topic < ApplicationRecord
  belongs_to :user
  has_many :comments
  has_one_attached :topic_image
  has_many :likes,dependent: :destroy
  belongs_to :category
  validates :content, presence:true
  after_update :approve_mail , if: :approved_changed?
  #after_update :disapprove_mail, if: :approved_changed?

  def approved_changed?
    saved_change_to_approved? 
  end

  def approve_mail
    UserMailer.approve_mail(self.user[:email]).deliver
  end

  def disapprove_mail
    UserMailer.disapprove_mail(self.user[:email]).deliver
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :topics, dependent: :destroy
  has_many :comments
  has_many :likes
  has_many :friend_sender, class_name: 'Friendship', foreign_key: 'sender_id'
  has_many :friend_receiver, class_name: 'Friendship', foreign_key: 'receiver_id'
  has_many :friends, through: :friend_receiver, source: :sender
  after_create :send_welcome_send

  ROLES = %w{super_admin admin}

  def super_admin?
    role == "super_admin"
  end

  def admin?
    role == "admin"
  end

  def send_welcome_send
    UserMailer.welcome_mail(self).deliver_now
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base


	protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  # http_basic_authenticate_with :name => "frodo", :password => "thering", :if => :admin_controller?

  # def admin_controller?
  #   self.class < ActiveAdmin::BaseController
  # end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password)}
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password)}
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  skip_before_action :verify_authenticity_token

  def index
    @topic = Topic.find(params[:topic_id])
  end

  def new
    @topic  = Topic.find(params[:topic_id])
    @comment = @topic.comments.new
  end

	def create
    @topic  = Topic.find(params[:topic_id])
  	@comment = @topic.comments.new(comment_params)
  	@comment.save
    if @comment.save
      redirect_to root_path
  	end
	end

  def show
    @topic = Topic.find(params[:topic_id])
  end

	private

	def comment_params
  	params.require(:comment).permit(:content,:topic_id,:user_id).merge(user_id: current_user.id)
  end
end

 

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index  
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
	  
  def new
  	topic = Topic.find(params[:topic])
  	if topic.likes.where(user_id: current_user.id).exists?
  		like = topic.likes.find_by(user_id: current_user.id)
  		like.destroy
  	else
  		like = Like.create(user_id: current_user.id,topic_id:params[:topic])
  	end
		redirect_to root_path
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
	#load_and_authorize_resource

	def index
		@topic = Topic.find_by(id: params[:id])
		if current_user.topics.count == 0
			flash.now[:notice] = "You have not created any post! Create one"
			render 'new'
		end
	end

	def new
		@topic = Topic.new
	end

	def create
		@topic = current_user.topics.build(topic_params)
		@topic.approved = false
		if @topic.save
			redirect_to @topic
		else
			flash.now[:error] = ('one of the field is missing')
			render :new, status: :unprocessable_entity
		end
	end

	def show
		@topic = Topic.new
	end
	# def show
	# 	@topic = current_user.topics.find(params[:id])
	# end

	def edit
    @topic = Topic.find_by(id: params[:id])
  end

	def update
		@topic = Topic.find_by(id: params[:id])

		if @topic.update(topic_params)
			redirect_to @topic
		else
			flash.now[:error] = ('one of the field is missing')
			render 'edit'
		end
	end

	def destroy
  	@topic = Topic.find(params[:id])
  	@topic.destroy
  	redirect_to root_path, status: :see_other
	end

	private
	
	def topic_params
		params.require(:topic).permit(:category_id,:title,:content,:topic_image).merge(user_id: current_user.id)
	end
end
  
 

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def index
		@users = User.all
	end

	def show
		#@user = User.find_by(name: params[:name])
		@user = User.where("name LIKE ?",params[:name] + "%")
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/likes/create.html.erb
<% flash.each do |type, msg| %>
  <div class="alert alert-info">
    <%= msg %>
  </div>
<% end %>

app/views/likes/index.html.erb
<% flash.each do |type, msg| %>
  <div class="alert alert-info">
    <%= msg %>
  </div>
<% end %>

app/views/topics/_form.html.erb
<section class="vh-100" style="background-color: #508bfc;">
  <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-12 col-md-8 col-lg-6 col-xl-5">
        <div class="card shadow-2-strong" style="border-radius: 1rem;">
          <div class="card-body p-5 text-center">
            <h1>Create New Post</h1>
            <%= form_with model: topic do |form| %>
              <div>
                <%= form.label :category_id %>
                <%= form.collection_select :category_id, Category.all, :id, :name, prompt: true %>
              </div>
              <div>
                <%= form.label :title %><br>
                <%= form.text_field :title %>
              </div>

              <div>
                <%= form.label :content %><br>
                <%= form.text_area :content %><br>
              </div>

              <div>
                <%= form.label :topic_image %><br>
                <%= form.file_field :topic_image %><br>
              </div>
              
              <div>
                <%= form.submit %>
              </div>
          <% end %> 
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/topics/edit.html.erb
<section class="vh-100" style="background-color: #508bfc;">
  <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-12 col-md-8 col-lg-6 col-xl-5">
        <div class="card shadow-2-strong" style="border-radius: 1rem;">
          <div class="card-body p-5 text-center">
            <h1>Edit Post</h1>
            <%= form_with model: @topic do |form| %>
              <div>
                  <%= form.label :category_id %>
                  <%= form.collection_select :category_id, Category.all, :id, :name, prompt: true %>
              </div>
              <div>
                <%= form.label :title %><br>
                <%= form.text_field :title %>
              </div>

              <div>
                <%= form.label :content %><br>
                <%= form.text_area :content %><br>
              </div>

              <div>
                <%= form.label :topic_image %><br>
                <%= form.file_field :topic_image %><br>
              </div>
              
              <div>
                <%= form.submit %>
              </div>
          <% end %> 
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/topics/index.html.erb
<button type="button" class="btn btn-info"><%= link_to "Create new post", new_user_topic_path(current_user.id) %><br></button>
<% Topic.where(user_id:current_user.id)&.each do |topic| %>
    <div class="card-group">
      <div class="card">
        <div class="card-body"> 
          <%if topic.topic_image.attached?%> 
            <%= image_tag topic&.topic_image,style: "width:250px;height:300px;" %>
          <% end %>
          <div class="p-3 border bg-light w-50">
          <h5 class="card-title"><b>Your_name:</b> <%= topic.user[:name]%></h5>
          <h5 class="card-title"><b>title:</b> <%= topic.title%></h5>
          <div class="row gx-5">
              <div class="col">
               <p class="card-text"> <b>content:</b><p style="font-size:20px;"><p class="card-text"><%= topic.content%></p></div>
              </div>
          <p class="card-text"><b>Posted On:</b><%= topic.updated_at%></p>
          <b>approved:</b><%= topic.approved%>
          </div>
        </div>
      </div>
    </div>
    <button type="button" class="btn btn-info"><%= link_to "Edit", edit_user_topic_path(current_user.id,topic.id) %><br></button>
    <button type="button" class="btn btn-danger">
    <%= link_to "Destroy", topic_path(topic), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %></button>
<% end %><br>
<button type="button" class="btn btn-warning"><%= link_to "Back", root_path %></button>


	

app/views/topics/new.html.erb
<% flash.each do |type, msg| %>
  <div class="alert alert-info">
    <%= msg %>
  </div>
<% end %>
<%= render "form", topic: @topic %>

app/views/topics/show.html.erb
<h1> You have not created any post </h1>

<button type="button" class="btn btn-info"><%= link_to "Create new post", new_user_topic_path(current_user.id) %><br></button>
<% Topic.where(user_id:current_user.id)&.each do |topic| %>
    <div class="card-group">
      <div class="card">
        <div class="card-body"> 
          <%if topic.topic_image.attached?%> 
            <%= image_tag topic&.topic_image,style: "width:250px;height:300px;" %>
          <% end %>
          <h5 class="card-title"><b>Your_name:</b> <%= topic.user[:name]%></h5>
          <h5 class="card-title"><b>title:</b><%= topic.title%></h5>
          <div class="row gx-5">
              <div class="col">
                <div class="p-3 border bg-light w-50"><p class="card-text"><b>content:</b><p style="font-size:20px;"><%= topic.content%></p></div>
              </div>
          </div>
          <p class="card-text"><b>Poste On:</b><%= topic.updated_at%></p>
          <p class="card-text"><b>approved:</b><%= topic.approved%></p>
        </div>
      </div>
    </div>
    <button type="button" class="btn btn-info"><%= link_to "Edit", edit_user_topic_path(current_user.id,topic.id) %><br></button>
    <button type="button" class="btn btn-danger">
    <%= link_to "Destroy", topic_path(topic), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %></button>
<% end %><br>
<button type="button" class="btn btn-warning"><%= link_to "Back", root_path %></button>