config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
 
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  # root "articles#index"
  root "home#index"
  
  devise_scope :user do  
    get '/users/sign_out' => 'devise/sessions#destroy'     
  end

  # scope "/:locale" do
  #   resources :users do 
  #     resources :topics
  #   end
  # end

  # resources :topics 
  resources :users

  resources :users do
    resources :topics do
      resources :likes
    end
  end

  resources :likes  
  
  resources :topics do 
    resources :comments
  end

  resources :users do
    resources :friendships
  end

  resources :friendships do
    member do
      get :delete
    end
  end

  resources :topics do
    member do
      get :show
    end
  end
  get '/users/', to: "users#show"
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the user here. For example:
    #
    #return unless user.admin?
    # can :read, :all
      return unless user.super_admin?
      can :manage, :all
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
	devise :database_authenticatable,:recoverable, :rememberable, :validatable

	ROLES = %w{super_admin admin}

  def super_admin?
    role == "super_admin"
  end

  def admin?
    role == "admin"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :topics
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :topic
  belongs_to :user
  validates :content,presence: true
end

app/models/friendship.rb
class Friendship < ApplicationRecord
	
	belongs_to :sender, class_name: 'User', foreign_key: 'sender_id'
	belongs_to :receiver, class_name: 'User', foreign_key: 'receiver_id'

end

app/models/like.rb
class Like < ApplicationRecord
  validates :user_id,uniqueness: {scope: :topic_id}
  belongs_to :user
  belongs_to :topic
end

app/models/topic.rb
class Topic < ApplicationRecord
  belongs_to :user
  has_many :comments
  has_one_attached :topic_image
  has_many :likes,dependent: :destroy
  belongs_to :category
  validates :content, presence:true
  after_update :approve_mail , if: :approved_changed?
  #after_update :disapprove_mail, if: :approved_changed?

  def approved_changed?
    saved_change_to_approved? 
  end

  def approve_mail
    UserMailer.approve_mail(self.user[:email]).deliver
  end

  def disapprove_mail
    UserMailer.disapprove_mail(self.user[:email]).deliver
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :topics, dependent: :destroy
  has_many :comments
  has_many :likes
  has_many :friend_sender, class_name: 'Friendship', foreign_key: 'sender_id'
  has_many :friend_receiver, class_name: 'Friendship', foreign_key: 'receiver_id'
  has_many :friends, through: :friend_receiver, source: :sender
  after_create :send_welcome_send

  ROLES = %w{super_admin admin}

  def super_admin?
    role == "super_admin"
  end

  def admin?
    role == "admin"
  end

  def send_welcome_send
    UserMailer.welcome_mail(self).deliver_now
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  skip_before_action :verify_authenticity_token

  def index
    @topic = Topic.find(params[:topic_id])
  end

  def new
    @topic  = Topic.find(params[:topic_id])
    @comment = @topic.comments.new
  end

	def create
    @topic  = Topic.find(params[:topic_id])
  	@comment = @topic.comments.new(comment_params)
  	@comment.save
    if @comment.save
      redirect_to root_path
  	end
	end

  def show
    @topic = Topic.find(params[:topic_id])
  end

	private

	def comment_params
  	params.require(:comment).permit(:content,:topic_id,:user_id).merge(user_id: current_user.id)
  end
end

 

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index  
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
	  
  def new
  	topic = Topic.find(params[:topic])
  	if topic.likes.where(user_id: current_user.id).exists?
  		like = topic.likes.find_by(user_id: current_user.id)
  		like.destroy
  	else
  		like = Like.create(user_id: current_user.id,topic_id:params[:topic])
  	end
		redirect_to root_path
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
	#load_and_authorize_resource

	def index
		@topic = Topic.find_by(id: params[:id])
		if current_user.topics.count == 0
			flash.now[:notice] = "You have not created any post! Create one"
			render 'new'
		end
	end

	def new
		@topic = Topic.new
	end

	def create
		@topic = current_user.topics.build(topic_params)
		@topic.approved = false
		if @topic.save
			redirect_to @topic
		else
			flash.now[:error] = ('one of the field is missing')
			render :new, status: :unprocessable_entity
		end
	end

	def show
		@topic = Topic.new
	end
	# def show
	# 	@topic = current_user.topics.find(params[:id])
	# end

	def edit
    @topic = Topic.find_by(id: params[:id])
  end

	def update
		@topic = Topic.find_by(id: params[:id])

		if @topic.update(topic_params)
			redirect_to @topic
		else
			flash.now[:error] = ('one of the field is missing')
			render 'edit'
		end
	end

	def destroy
  	@topic = Topic.find(params[:id])
  	@topic.destroy
  	redirect_to root_path, status: :see_other
	end

	private
	
	def topic_params
		params.require(:topic).permit(:category_id,:title,:content,:topic_image).merge(user_id: current_user.id)
	end
end
  
 

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def index
		@users = User.all
	end

	def show
		#@user = User.find_by(name: params[:name])
		@user = User.where("name LIKE ?",params[:name] + "%")
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<!-- Automatic Slideshow Images -->
<div class="mySlides w3-display-container w3-center">
  <%= image_tag ("layout/culture.jpg"),style:"width:100%;height:100%;" %>
</div>
 
<h1> Welcome to online forum </h1>
<h1><%= t(:hello) %></h1>
<% if user_signed_in? %>
	<% Topic.where(approved:true).order(updated_at: :asc)&.each do |topic| %>  
		<div class="card bg-dark text-white">
  			<div class="card">
    			<div class="card-body">
    				<%if topic&.topic_image&.attached?%> 
            		<%= image_tag topic&.topic_image,style: "width:250px;height:300px;" %>
          		<% end %>
     				<div class="p-3 border bg-light w-50">
      				<p style="font-size:25px;"><%= topic.title%></p>
      				<div class="row gx-5">
    					<div class="col">
    						<blockquote class="blockquote mb-0">
      						<b>content:</b><p><%= topic.content%></p>
      						<footer class="blockquote-footer">written by<cite title="Source Title"> <%=topic.user[:name]%></cite> <p class="m-1">Posted on: <cite title="Source Title"><%= "#{time_ago_in_words(topic.created_at)} ago" %></cite></p></footer>
    						</blockquote>
    					</div>
  					</div>	
      		</div>
      		<%= topic.likes.count %>	
      		<%= link_to "Like", new_like_url(current_user: current_user,topic: topic), method: :post %>
     		</div>
					<h2>Comments</h2>
					<% topic.comments.each do |comment| %>
					  <p>
					    <strong>Comment by <%=comment.user.name%>:</strong>
					    <%= comment.content %>
					  </p>
					<% end %>
					<div class="card my-1">
					  <div class="card-body">
					    <%= form_with(model: [topic, topic.comments.build]) do |f| %>
					      <div class="form-group">
					        <%= f.label 'New comment' %>
					        <%= f.text_area :content, class: 'form-control' %>
					      </div>
					      <%= f.submit 'Submit', class: 'btn btn-primary' %>
					    <% end %>
					  </div>
					</div>
  			</div>
    </div>
	<% end %>
<%end%>

	